import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NotistackProvider from "../src/Providers/NotistackProvider";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Event_Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <NotistackProvider>
          {children}
        </NotistackProvider>
      </body>
    </html>
  );
}
